### ISSUE TITLE
Add "omero-archive" topic?

### ISSUE THREAD

**Issue by joshmoore** [aherbert/omero-archiving#1]
Cf: https://github.com/Laura190/OMEROimport/issues/1

In order to have this repository show up under a search for "omero" topics:

https://github.com/search?q=omero&type=topics

would you consider adding the "omero-archive" topic to the repo? (Other suggestions welcome)

**Comment by aherbert** [comment]
Done.

**Comment by joshmoore** [comment]
:heart:
